site_name: My Docs
theme:
  name: material
  features:
    - navigation.instant
    - navigation.expand
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - attr_list
  - tables
  # - grid_tables
  - pymdownx.highlight
      # linenums: true
      # linenums_style: pymdownx.inline
  - pymdownx.superfences
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - css/custom-elements.css
  - css/material-colors.css
  - css/material-shadows.css
  - css/material-components.css
nav:
  - Home: 'index.md'
  - About: 'about.md'
  - Summaries:
    - Software Design: 
      - Overview: 'software design/overview.md'
      - Factory: 'software design/factory.md'
    - Algorithms Lab:
      - Prefix Sum and Precomputation: 'Algorithms Lab/prefix_sum_and_precomputation.md'
      - Sliding Window: 'Algorithms Lab/sliding_window.md'
      - Dynamic Programming: 'Algorithms Lab/dynamic_programming.md'
      - 'Numbers: Representation and Computation (CGAL)': 'Algorithms Lab/numbers_and_computation.md'
      - Geometric Computing: 'Algorithms Lab/geometric_computing.md'
      - Boost Graph Library: 'Algorithms Lab/boost_graph_library.md'
      - Greedy Algorithms: 'Algorithms Lab/greedy.md'
      - Proximity Structures: 'Algorithms Lab/proximity_structures.md'
      - Exercises:
        - week 1: 'Algorithms Lab/exercises/w01.md'
        - week 2: 'Algorithms Lab/exercises/w02.md'
        - week 3: 'Algorithms Lab/exercises/w03.md'
        - week 4: 'Algorithms Lab/exercises/w04.md'
        - week 5: 'Algorithms Lab/exercises/w05.md'
        - week 7: 'Algorithms Lab/exercises/w07.md'
        - week 8: 'Algorithms Lab/exercises/w08.md'
      - Problems of the week: 'Algorithms Lab/pows/pows.md'
  - Notes:
    - Flutter:
      - Setup: 'notes/flutter/02_setup.md'
      - I am rich: 'notes/flutter/03_app_from_scratch.md'
      - MiCard: 'notes/flutter/06_MiCard.md'
      - Dicee - Building Apps with State: 'notes/flutter/07_dicee.md'
      - Xylophone - Using Flutter and Dart Packages: 'notes/flutter/09_xylophone.md'
      - Quizzler - Modularising & Organizing Flutter Code: 'notes/flutter/10_quizzler.md'
      - BMI Calculator - Building Flutter UIs for Intermediates: 'notes/flutter/12_bmi.md'
      - Clima - Powering Your Flutter App with Live Weather Web Data: 'notes/flutter/13_clima.md'
      - Bitcoin Ticker: 'notes/flutter/14_bitcoin.md'
      - Chat App w. Firebase: 'notes/flutter/15_chat.md'
      - Todoey - State Management: 'notes/flutter/16_todoey.md'

  # - Home: /docs/index.md