site_name: My Docs
theme:
  name: material
  features:
    - navigation.instant
    - navigation.expand
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - attr_list
  - tables
  - pymdownx.highlight
      # linenums: true
      # linenums_style: pymdownx.inline
  - pymdownx.superfences
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - css/custom-elements.css
  - css/material-colors.css
  - css/material-shadows.css
  - css/material-components.css
nav:
  - Home: 'index.md'
  - About: 'about.md'
  - Summaries:
    - Software Design: 
      - Overview: 'software design/overview.md'
      - Factory: 'software design/factory.md'
    - Algorithms Lab:
      - Prefix Sum and Precomputation: 'Algorithms Lab/prefix_sum_and_precomputation.md'
      - Exercises:
        - week 1: 'Algorithms Lab/exercises/w01.md'
  - Notes:
    - Flutter:
      - Setup: 'notes/flutter/02_setup.md'
  # - Home: /docs/index.md